### ISSUE TITLE
Make external links easier to identify

### ISSUE THREAD

**Issue by carbontwelve** [photogabble/website#174]
Currently its difficult to tell if a link is internal or external, add a flair to external links so that they can be identified visually.

**Comment by carbontwelve** [comment]
This code snippet from https://davidwalsh.name/external-links-css might do the trick:

```css
a[href^="http://"]:not([href*="mydomain.com"]):before{ 
    content: " ";
    width: 16px;
    height: 16px;
    background: no-repeat url('images/link.gif'); 
    padding-right: 1.2em;
}
```
